openinput-fw/openinput

- .gitmodules
Added CMSIS 5, STM32F1 CMSIS device pack, and TinyUSB as submodules.
> submodules: added external dependencies as submodules

- .github/workflows/build.yml
- .pre-commit-config.yaml
- build_targets/__init__.py
- build_targets/families.py
- build_targets/targets.py
- configure.py
- src/hal/hid.h
- src/platform/generic/platform-hid.h
- src/platform/linux-uhid/hal/hid.c
- src/platform/linux-uhid/hid.c
- src/platform/linux-uhid/hid.h
- src/platform/linux-uhid/uhid.c
- src/platform/linux-uhid/uhid.h
- src/targets/linux-uhid/main.c
- src/util/types.h
>  linux-uhid: initial implementation 

- .clang-format
- .github/workflows/build.yml
- build_targets/__init__.py
- build_targets/families.py
- build_targets/targets.py
- src/platform/stm32f1/rcc.c
- src/platform/stm32f1/rcc.h
- src/targets/stm32f1-generic/config/bluepill.h
- src/targets/stm32f1-generic/config/generic.h
- src/targets/stm32f1-generic/main.c
- src/util/data.h
> stm32f1-generic: setup clocks

- src/platform/stm32f1/rcc.c
- src/platform/stm32f1/rcc.h
> STM32F1 add rcc clock tree

- src/platform/stm32f1/rcc.c
> stm32f1: rcc: enable pll

- .github/workflows/build.yml
- configure.py
> ci: clone submodules

- .gitmodules
- build_targets/dependencies.py
- build_targets/families.py
- src/targets/stm32f1-generic/config/bluepill.h
- src/targets/stm32f1-generic/config/rival310.h
- src/targets/stm32f1-generic/main.c
Not sure we want this how it is right now (do we want to have blobs on the repo?), but works for testing the sensors
> Add Sensor Code

- src/driver/pixart/pixart_pmw.c
> driver: pixart: fix fault on pmw_init

- .github/workflows/build.yml
- .github/workflows/check.yml
> github: change repo name

- src/driver/pixart/pixart_pmw.c
- src/driver/pixart/pixart_pmw.h
- src/hal/spi.h
- src/hal/ticks.h
- src/platform/stm32f1/atomic.h
- src/platform/stm32f1/exceptions.c
- src/platform/stm32f1/flash.c
- src/platform/stm32f1/flash.h
- src/platform/stm32f1/gpio.c
- src/platform/stm32f1/gpio.h
- src/platform/stm32f1/hal/spi.c
- src/platform/stm32f1/hal/spi.h
- src/platform/stm32f1/hal/ticks.c
- src/platform/stm32f1/hal/ticks.h
- src/platform/stm32f1/spi.c
- src/platform/stm32f1/spi.h
- src/platform/stm32f1/startup.c
- src/platform/stm32f1/systick.c
- src/platform/stm32f1/systick.h
- src/platform/stm32f1/usb_descriptors.c
- src/targets/stm32f1-generic/config/bluepill.h
- src/targets/stm32f1-generic/config/rival310.h
> copyright: update contact email address

- build_targets/families.py
- build_targets/linker/stm32f1-generic/common.ld
- src/platform/stm32f1/hal/hid.c
- src/platform/stm32f1/hal/hid.h
- src/platform/stm32f1/startup.c
- src/platform/stm32f1/usb.c
- src/platform/stm32f1/usb.h
- src/platform/stm32f1/usb_descriptors.c
- src/targets/stm32f1-generic/main.c
- src/targets/stm32f1-generic/tusb_config.h
> stm32f1 openinput protocol

- .github/workflows/build.yml
- .gitmodules
- build_targets/dependencies.py
- build_targets/families.py
- build_targets/linker/efm32gg12-generic/common.ld
- build_targets/linker/efm32gg12-generic/efm32gg12bxxxf1024.ld
- build_targets/linker/efm32gg12-generic/efm32gg12bxxxf512.ld
- build_targets/linker/efm32gg12-generic/sltb009a.ld
- build_targets/targets.py
- src/platform/efm32gg/atomic.h
- src/platform/efm32gg/cmu.c
- src/platform/efm32gg/cmu.h
- src/platform/efm32gg/emu.c
- src/platform/efm32gg/emu.h
- src/platform/efm32gg/gpio.c
- src/platform/efm32gg/gpio.h
- src/platform/efm32gg/hal/hid.c
- src/platform/efm32gg/hal/hid.h
- src/platform/efm32gg/startup.c
- src/platform/efm32gg/systick.c
- src/platform/efm32gg/systick.h
- src/platform/efm32gg/usb.c
- src/platform/efm32gg/usb.h
- src/platform/efm32gg/usb_descriptors.c
- src/platform/stm32f1/usb_descriptors.c
- src/targets/efm32gg12-generic/config/sltb009a.h
- src/targets/efm32gg12-generic/main.c
- src/targets/efm32gg12-generic/tusb_config.h
Add support for the efm32 giant gecko family
> Platform efm32gg

- src/platform/efm32gg/usb_descriptors.c
> platform: efm32gg: add out endpoint

- docs/assets/logo_icon.svg
> docs/assets: add icon only logo

- README.md
- docs/index.rst
> readme/docs: update progress

- docs/index.rst
- src/platform/stm32f1/exceptions.c
>  stm32f1: align exceptions 

- docs/index.rst
> docs: update protocol url

- src/platform/stm32f1/driver/led_pwm.c
- src/platform/stm32f1/driver/led_pwm.h
> stm32f1: timer based pwm led driver

- src/driver/pixart/pixart_pmw.c
- src/driver/pixart/pixart_pmw.h
> driver: pixar_pmw: initialization changes and cpi change support

- .github/CODEOWNERS
> codeowners: update to new build system and targets

- docs/index.rst
> docs: update roadmap

- src/platform/efm32gg/cmu.c
- src/platform/efm32gg/emu.c
- src/platform/stm32f1/spi.c
> platform: fix clang-format

- docs/contributing/index.rst
- docs/index.rst
> Add contributing guide

- .github/workflows/test.yml
- .gitignore
- README.md
- codecov.yml
- config/families/testsuite.toml
- config/targets/testsuite.toml
- configure.py
- noxfile.py
- src/protocol/protocol.h
- src/targets/testsuite/main.c
- tests/conftest.py
- tests/test_protocol.py
- tests/unmet-dependencies.py
- tests/wrapper/_testsuite.c
- tests/wrapper/pages.py
- tests/wrapper/setup.py
- tests/wrapper/testsuite.py
> Add test suite

- .github/workflows/build.yml
- .github/workflows/test.yml
> ci: skip source workflows on documentation changes

- .github/workflows/lint.yml
> ci: fix lint workflow name

- configure.py
- noxfile.py
- src/protocol/protocol.c
- tests/conftest.py
- tests/test_protocol.py
- tests/wrapper/_testsuite.c
- tests/wrapper/testsuite.py
> Add tests for protocol dispatch and INFO FW_INFO

- .gitignore
> gitignore: add *.so

- docs/index.rst
- docs/reference/hals.rst
- docs/reference/index.rst
- src/hal/hid.h
> docs: add HALs

- src/hal/spi.h
- src/hal/ticks.h
Signed-off-by: perigoso <perigoso@riseup.net>
> Add documentation for ticks and spi hal

- src/targets/testsuite/main.c
> targets: testsuite: remove leftover code

- README.md
> readme: add LPC11U3x target

- .github/workflows/test.yml
- noxfile.py
> nox: run fuzz session with address, memory and undefined sanitizers

- config/base.toml
> Color diagnostics
